apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-app
  template:
    spec:
      containers:
      - name: argocd-app-container
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: dev-mysql-app-secret
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: dev-mysql-app-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dev-mysql-app-secret
                key: MYSQL_PASSWORD