apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: dev
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgCd6j9aw97ar4rvcLk+jimO4b0UTRKMZTxzkQrrwtzEU4aWx75vcwdX9rhQAG4r4stnOr4DonSOviNACSjjqqDICI8G/5Og0EOdJ2YWbQpefTqnXM/QLXIvZu2dSQru7haTC+DBmbYfzkwm+zOUjGFLsQXmQipJuoOJvkyrrl+jsT4neENu0jg5Dc9m/iWWmvhpebgTi5Df2BcnW8p2bcCc0oSJ59IMZl5P3Yz78znmA/FDx2pPVtPe/yy22geUBSqOZeV/9Kj55r8TB7WUoTMSvojagxXdGTq/SGfHXExpJoriYnHzHNSuSIXx7LBG+Zij2Jx/WStGoGTnYtpjA2h/08XzNC1eevIw3YnETfiWQOmm/GkDMFjzS+4O6Qmq9TxrFt1oSkl+nJ3655tZBjCFgkozYv2RGIZxgyLv9auYXL8XCObgM/k+e8d7s0H+ItGyPImmfuO+Y8e5v8HKfilnopa6kk43Tho7k0NJjTXJlP09qYGhQm9LUfsVNLrXFPL8+Cc1bQQp/XZ+/njX1vD+1H9dAz5p+fsYVcc+w6r4HsuvZbq+kQMgzweZJ4nk4c3O6WFPXb2PM0FvlQBWeoa956zldTxdBvotx9IVNpxcrY8vzcx/dDPisOvBPZ5ChPpKjihyuK3xnIB909F5A1Pff61RJk4bDIDXL2cmZdaUMwq476OmsCVwXYMOA3xErrSRdFgN4VI7qQjz
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: dev