apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: dev
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgAKM1iEUSwjQOOkrtLzferGGDaGcQ8KGLChtOYAxFd1rYmbyjJQ3EPqCjOD4FQAZL67n7irvSXU7QUvI0KdfWPtYOqqTPW5yqebriJXfSfDfEgOO5ECUJLBKGaQI5fxBcQCuRyyiScUH/EheoFzs29lHan3DNAPfgZnFE3Lvxh/AYZTseM53OG4N9D+taCwcEbzW/g172VVsIw6oYzpzdYflqi+93fIsmkECZtcHDOsYZh3BEyJK8CEXoNt1G6OW/lNtyGqEZ3sPD5UMUphnqxTubiSM8klct/op6nvH3009a17It+qpCo49VYZQu74baMRIZ3WrkVjIrCSxAwX87dqAt0S9Lh3R3LFqwY0u4ezBNdloKt36ztNLRqbbfxs1KyEFdcAewBakJDxvx2d9UIX5B7XywKXDE0QJjVYSTV7XxVGMaj5y40U0OGXCGppxpU5m88GsUINza6caPe7fbQdUN/6T62Yzal370E87FEkz74L7bIubs6tfG+TLUfH0N3gtD7zDeWj9klXsVXXiGNGs3NQNc7aPWdSd+Q64dCvr7VseRGQdUe2ed0YKvlFwFdmRGAOIM2Xk5EufX7ZuGJ5R+ZHMw7Nu5/AYnnNMrbHPFvmeYBRg5Jth/QgvclBH3Ou7BCqqzZrKYlRn16YsPksUdDHti3HgymjuJjKdI9sLoYjF+26r5FMKcr+nhRXhj+WW/YsWWdTD7I/
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: dev