apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-secret
  namespace: dev
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgB9R3rhSHm1CSOHyZRcp/KIidQ85du9AwpqKSaALX0qnahXwLQvUsJZSinVTRGv7SH2Q3J9pJS7DRlyE4xbhOPcHjXIJ+MYkH80WPGecpp3nC132u/t3UwXMLoVIXSg+hhZt7hJuWIfYSG/6yJW4wQ11R7Gv75mM1iSfH2HATbHTlR1Djbdg+AeTKW+T6blZ0sXD0EuFFMCNO9KvSiAc3W81zuqUkO878yCkyoKQ7aWwkvriXMvJYV5Deyl6NFrMjQcu235VMrDm85tO1cMqCtU3knhxC135Kjlflzk/wV/Oia8UzQnZ0RLmWpw1l44ipzadwnAAsLcFttgGRcFhtwH2ezxM8P8Lkmp251phMmDcMQqkj/zJe5cDmeGAXUTfctz6w84qq1Ht7mFJmwcbloBvcbu8Wg0MzfO/8tvFfZbo/my0DevJWVjHoLtSfZaJ+VR8V3kYBcwmA4/Jz10l43+W9bSeB26NTCJ1Z23EJbRBfpKx/JoZrDnSbEA/f98wfPdpM5aH1PqogqtizYd0pgWWvKPlHN8UeWvJRzEF/JL7ZVMx9k3dsbVeCS5tAE6uZyKSCrIdH9VRwHaNyHg8o5jUJyKq8+clBds8AwQ02Q/bfAy/kk7BbpT0T9oLg74kQNL2W+ght4oKRa3F7F9ndR5kJxw4POB2a214DaGiW1pYbmZdmGouybGzbd+873iwshy2vzD8m3T34pf
  template:
    metadata:
      creationTimestamp: null
      name: mysql-secret
      namespace: dev