apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mysql-secret
  namespace: dev
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgB/ct0/Qql+9NXueR4a/oFXuJYLmk3qOricQ7q2eZ+IyNXIWiqUHROu/xTpNHSPRiBAzw4rKyQTiWVBsjw3Gj209GhEHQO+z7ffM/uVdiZ5JdLG88ats2qn2YRwQevVoALplUL7h4cwRtud+oDhNqhNEiXJmGFfX1OAso8U5ZBDHAKqWNqutQI0/Yh8cZDhKT94SOhs+CKCCggEWImzf1+Gm51vvkxfjbCHODSjUDll9AZzBTJOfC+7by9LvzmOlQ8WeAL6R4ea1x0X2UsUmW1VjIdCcQvvzKQbqUIj8BmcSWpMg8D0AHJMktAed2f4t9OCuWMo5o6f05cfkjYkz2hAFa33WUinr8iSiYQoeM9opZEWsxe90jkvsHmYXKgGaDnmJTQm+tD5cfhNdq/+es4Uwj6fGWtMZj/jWF3nwAIZW59903FnjgIkLYCSvQqRfDRgoVQ0CMq6zFTNGRrKdInziH1mwT9Zo4Me5GMK9vcwlCpsGGGYHsktDBNlAx5BIUlEjmNMbqT/0d2go3IKmwNszMrRCELUMEmo7j+2T28KQ6fZyHCd3aEolJ8LqwdazAQl5zvk+s5xrCcCDO+39FFDm5F1b9xUavA8uxI6KhFeDajwJsc9TaArCJ2Bm0yr72BHOMf4ly0bO3oDbyX9uPbvS/fjLvGIFVSFrj2hsKly48SdROIqP90cyrogDWGtYcfMpTrAaD3v7/p8
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mysql-secret
      namespace: dev