apiVersion: v1
kind: Service   
metadata:
  name: argocd-app-service
spec:
  selector:
    app.kubernetes.io/name: argocd-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-app
    spec:
      containers:
      - name: argocd-app-container
        image: siyunp/app-with-argocd-kustomize:e094905
        ports:
        - protocol: TCP
          containerPort: 8080
        env:
        - name: MYSQL_DATABASE_URL
          value: jdbc:mysql://mysql-service:3306/myappdb
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-app-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-app-secret
              key: MYSQL_PASSWORD
