apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app-deployment
spec:
  template:
    spec:
      containers:
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: prod-mysql-app-secret
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: prod-mysql-app-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prod-mysql-app-secret
                key: MYSQL_PASSWORD