apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-app
  template:
    spec:
      containers:
      - name: argocd-app-container
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://prod-mysql-service:3306/myappdb
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: prod-mysql-app-secret
                key: MYSQL_USER
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prod-mysql-app-secret
                key: MYSQL_PASSWORD