name: App With Github Actions with ArgoCD

on:
  # workflow_dispatch:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Make application.properties
      run: |
        mkdir -p ./app/src/main/resources
        echo "${{ secrets.PROPERTIES }}" > ./app/src/main/resources/application.properties
      shell: bash

    - name: Build with Maven
      run: mvn -B -DskipTests package --file app/pom.xml
      
    - name: Naming jar file
      run: mv ./app/target/*.jar ./app/target/app.jar

    - name: Check jar file
      run: ls ./app/target

    - uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./app/target/*.jar

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Set SHORT_SHA env
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./app
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.SHORT_SHA }}

  cd:
    runs-on: ubuntu-latest

    needs: ci
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        token: ${{ secrets.GH_TOKEN }}
        
    - name: Set SHORT_SHA env
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
    
    - name: Show original image line
      run: grep "image:" ./manifest/base/argocd-app/argocd-app.yaml

    - name: Set up Image
      run: |
        sed -i "s%image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:.*%image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ env.SHORT_SHA }}%" ./manifest/base/argocd-app/argocd-app.yaml

    - name: Show modified image line
      run: grep "image:" ./manifest/base/argocd-app/argocd-app.yaml
      
    - name: Commit and push changes
      run: |
        git config --local user.email "eqeee@naver.com"
        git config --local user.name "siiiirru"
        git add .
        git commit -m "Update nginx image to latest"
        git push